### ISSUE TITLE
Status update: Unable to connect. Reason: Registration Missing

### ISSUE THREAD

**Issue by VergeDX** [Boostport/setup-cloudflare-warp#37]
Same issues as:  
https://community.cloudflare.com/t/unable-to-use-warp-cli-on-ubuntu-possible-bug/553815
https://community.cloudflare.com/t/github-actions-and-warp/507115

**Comment by F21** [comment]
From past experience, this happens when:
- The credentials provided are expired or incorrect.
- There's an issue on Cloudflare's end and is resolved after cancelling and restarting the job.

**Comment by giriparus** [comment]
I have ensured that the below cases do not apply.

- The credentials provided are expired or incorrect.
- There's an issue on Cloudflare's end and is resolved after cancelling and restarting the job.

I have also setup the policy as stated [here](https://developers.cloudflare.com/cloudflare-one/connections/connect-devices/warp/deployment/device-enrollment/#example-policies). 

I still face this issue and the action keeps running forever.
It might be important to note that logs show the correct organization.

**Comment by saaskitten** [comment]
> I have ensured that the below cases do not apply.
> 
> * The credentials provided are expired or incorrect.
> * There's an issue on Cloudflare's end and is resolved after cancelling and restarting the job.
> 
> I have also setup the policy as stated [here](https://developers.cloudflare.com/cloudflare-one/connections/connect-devices/warp/deployment/device-enrollment/#example-policies).
> 
> I still face this issue and the action keeps running forever. It might be important to note that logs show the correct organization.

Facing the same, wondering if we're missing something else.

**Comment by londek** [comment]
I face exactly the same issue, service token is fresh and valid and proper policies are in place...

**Comment by giriparus** [comment]
I resorted to use [this action](https://github.com/oHTGo/setup-cloudflare-warp-action) instead. I can confirm this is working for me.
